project:
  type: website
  resources: assets
  output-dir: docs
  
# execute:
#   freeze: auto  # Re-render only when source changes

website:
  title: "Your Name"
  navbar:
    background: "#341648"
    foreground: "#eaaa00"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
    right:
      - icon: file-pdf
        href: assets/resume.pdf
      - icon: github
        href: https://github.com
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    theme: 
      - default
      # - custom.scss
    # backgroundcolor: lightgray
    css: styles.css
    toc: true



